#!/bin/sh
# shellcheck disable=SC2164

YELLOW='\033[1;33m'
NC='\033[0m' # No Color

if [ ! -d "$PROJECTS/$1" ]; then
  echo "🔥 ${YELLOW}$PROJECTS/$1${NC} not found, try cloning it first 😉" >&2
  return 1
fi

cd "$PROJECTS/$1"
