#!/usr/bin/env python
#
# Generate random hex encoded string
#
# Usage: mk_api_key <key length>
#

import sys
import random
import string

if len(sys.argv) > 1:
  size = int(sys.argv[1])
else:
  size = 16

print ''.join([
  random.SystemRandom().choice("{}{}{}".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(size)
]).encode('hex')
