#!/usr/bin/env python

import sys
import random
import string

if len(argv) > 1:
  size = argv[1]
else:
  size = 16

print ''.join([
  random.SystemRandom().choice("{}{}{}".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(size)
]).encode('hex')
