#!/usr/bin/env python

import random
import string

print 'SECRET_KEY=\"%s\"'%''.join([
  random.SystemRandom().choice(\"{}{}{}\".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(63)
])
