#!/usr/bin/env python
#
# Generate random Django SECRET_KEY
#
# Usage: mk_dj_secret
#

import random
import string

print 'SECRET_KEY=\"%s\"'%''.join([
  random.SystemRandom().choice(\"{}{}{}\".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(63)
])
