#!/usr/bin/env bash

# Using .pyenvrc file generated by markosamuli.pyenv Ansible role
if [ -e "$HOME/.pyenv/.pyenvrc" ]; then
  source $HOME/.pyenv/.pyenvrc
fi

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
